### ISSUE TITLE
Add a Sign Out button

### ISSUE THREAD

**Issue by NeighborGeek** [lithnet/laps-web#1]
After logging in to LAPSWeb, there doesn't appear to be any way to sign out.  Even after closing the tab and browsing to our LAPSWeb site in a new browser window, it still seems to be signed in. 

There should be a link or button to explicitly sign out of the site and show a confirmation that the user has been signed out.  Also, sign in should not persist beyond the browser session.  If I close the tab or window and browse back to the site, I should always be prompted to sign in again.

**Comment by ryannewington** [comment]
Are you using an external authentication provider or integrated windows auth?

**Comment by NeighborGeek** [comment]
Windows Authentication

**Comment by ryannewington** [comment]
The problem with IWA is the authentication happens between IIS and your browser, and the web site doesn't participate in that. There technically isn't a way for the web app to sign you out. You do need to close your browser to have it 'forget' the session it set up with the web server.

Depending on your browser settings, you might even get signed in immediately when visiting the site, without a password prompt at all.

When using an external authentication provider, the sign out button does indeed appear, as we can terminate the session and cookies associated with your login session. IWA has no such concept.

**Comment by NeighborGeek** [comment]
That's kind of scary.  I could see a case where an IT person borrows a user's computer (already signed in as the user) for a moment, logs in to LAPSWeb (using their IT credentials) to look up a password, and then closes the window thinking they are signed out.  If the user were to pull the site up later, perhaps from their history, it would still be logged in as the IT person and give the user access to LAPS passwords.

What if we configure Authentication to use AzureAD instead?  Will that present a method to explicitly sign out of LAPSWeb?

**Comment by ryannewington** [comment]
@NeighborGeek Yes it's not great. I've provided the functionality so people have choice. But I do recommend AzureAD instead. The signout button appears when using a provider that supports logoout (eg Azure AD or ADFS).
