### ISSUE TITLE
Add a field to capture the reason for the LAPS request

### ISSUE THREAD

**Issue by colorenz** [lithnet/laps-web#11]
Hello,

I would like to add a text box. So that a reason can be given why the password was retrieved. I would also like to copy this text to Loggin. How can I implement this?

**Comment by dlsmlss** [comment]
I have a little bit more to say on this enhancement.
Can it be looks like Windows Server 2003 shutdow dialog? I mean with some "predefined" reasons (that could be configured throught web.config) and "Other reason" that "activate" text box to fill reason manualy.
Thanks!

**Comment by dlsmlss** [comment]
Also have one more thing to add - reason can be optional or requred (also can be configured throught web.config).

**Comment by red-erik** [comment]
Hello,
any news on this topic ?

Regards,
Red.

**Comment by ryannewington** [comment]
Hi all,

I've implemented this feature in the replacement for laps-web, which is now Lithnet Access Manager. You can check out the feature in the beta version released today.

https://github.com/lithnet/access-manager/releases/tag/v1.0.7596-beta.1

Ryan
