### ISSUE TITLE
Select users can only access selected computers LAPS Password

### ISSUE THREAD

**Issue by GregoryMachin** [lithnet/laps-web#14]
Hi, 
This is a feature request. 
It seems that all the tools for LAPS are all or nothing, effectively a user that has access to the stored LAPS passwords has access to all computer objects LAPS passwords. This is fine for the IT support team, but not for special use cases. 

Would it be possible to have a configuration where an authenticated user can be assigned a list of devices that they can retrieve the LAPS password for, but no other devices?

**Comment by dlsmlss** [comment]
1. You can do you request with LAPS with out any problems. 
- create user group and include needed users to it
- move "needed" computer to different OU
- disable inheretence 
- create new delegation for those 2 attributes for newly created group
- profit
2. You can do it this task without any laps-web product improvements
https://github.com/lithnet/laps-web/wiki/Permissions
just take a look at configuration file
    <target name="COMPUTER-NAME-HERE" 
            type="Computer" 
            expire-after="01:00:00">
      <audit emailAddresses="security-team@lithnet.io"/>
      <readers>
        <reader principal="DOMAIN\User or group" />
     </readers>
    </target>

Just add targets as many as you want and use GMSA for running the AppPool and dont forget to deligate attributes for it

**Comment by ryannewington** [comment]
@dlsmlss is correct. A target does not have to be an OU, it can be a group containing computer objects, or even a single computer object itself.

https://github.com/lithnet/laps-web/wiki/Permissions

Have a look at the 'Web servers' example in the page above. I think that is what you are after, but if not, let me know.

**Comment by ryannewington** [comment]
Closing this issue. Please reopen if you need additional help.
