### ISSUE TITLE
Cannot find computer in AD With message requested access to computer XXXX$ but no targets exist for this computer

### ISSUE THREAD

**Issue by RonnyPetersson** [lithnet/laps-web#15]
I made all the settings according to the manual but I can not see the password and the log shows the following message:

Requested access to computer XXXX$ but no targets exist for this computer

**Comment by RonnyPetersson** [comment]
@ryannewington I sent I sent to your email the XML and log files.

Thanks

**Comment by ryannewington** [comment]
Hi @RonnyPetersson,

Two problems

1. The '<targets>' element in your config file is commented out. Remove the `<!--` and `-->` to uncomment.

```xml
  <!--
    <targets>
...
    </targets>
    -->
```

2. The `target name` attribute is missing `OU=` in front of `OU=Desktops`

**Comment by RonnyPetersson** [comment]
Hi @ryannewington ,
                             I made the adjustments and the error is now another:

**The requested computer does not have a LAPS password** 

In GUI LAPS I usually refer to the password.
Thanks

**Comment by ryannewington** [comment]
@RonnyPetersson,

That message appears if the service account that the web site is using doesn't have permissions to read the LAPS password from the directory.

https://github.com/lithnet/laps-web/wiki/Configure-LAPS-service-account-permissions.

Ryan

**Comment by RonnyPetersson** [comment]
Hi @ryannewington ,
                   I set the permissions and the error is the same

**Comment by RonnyPetersson** [comment]
Hi @ryannewington , I configured a service account for login as a job and service and Lapseweb successful password query.
Thanks
