### ISSUE TITLE
Prompt for credentials

### ISSUE THREAD

**Issue by mgorski10** [lithnet/laps-web#16]
I am wondering if it is possible to have the web app prompt for credentials when accessing the website instead of using SSO.  I have implemented the web app and it works well but since i have access to it tied to my user's privileged admin domain accounts, they are complaining of the need to launch a browser as that account as opposed to being allowed to navigate to the site and have access right away.  Thanks.

**Comment by ryannewington** [comment]
Do you have adfs or azure ad? You can delegate authentication to either of those of that it an option?

**Comment by mgorski10** [comment]
Thanks for responding. I'll don't believe we are yet and so will need to check. But if we are, how do you mean delegate authentication?  From what I understand, wouldn't that be the same as if we granted access to user's non privileged account vs the privileged one in the web.config?


Sent via the Samsung Galaxy Note9, an AT&T 5G Evolution capable smartphone

-------- Original message --------

**Comment by ryannewington** [comment]
When you have the web app hand off the authentication process to AzureAD/ADFS, those services will prompt for a username and password, and return the authorization information back to the web app. They can log into those services with their privileged account when prompted. An added bonus is that if those services support MFA, you can inherit that additional protection.

This page talks about how to configure the app to use an external authentication provider.

https://github.com/lithnet/laps-web/wiki/Authentication-options

I can take a look at what the effort would be to introduce forms-based authentication if that's not an option for you. That would be an in-app login page. There is a fair bit of work involved in that, so it won't be something I can get you straight away.
