### ISSUE TITLE
Azure AD Authentication 

### ISSUE THREAD

**Issue by hbamford** [lithnet/laps-web#17]
When setting up Azure AD as the Authentication method i am getting the below error message 

> An authentication error occurred 
> 
> IDX21323: RequireNonce is '[PII is hidden]'. OpenIdConnectProtocolValidationContext.Nonce was null, OpenIdConnectProtocol.ValidatedIdToken.Payload.Nonce was not null. The nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'. Note if a 'nonce' is found it will be evaluated.

**Comment by ryannewington** [comment]
Hey @hbamford 
This usually caused by a cookie problem. Any blockers in use in your browser? Does it happen across all browsers?
