### ISSUE TITLE
Revoke permissions

### ISSUE THREAD

**Issue by skysbsb** [lithnet/laps-web#18]
hello, how do i undo delegate permission for the service user?

I gave permission by running the following command:

dsacls "dc = rond, dc = local" / G "rond.local \ david: CA; ms-Mcs-AdmPwd; computer" / I: S

**Comment by ryannewington** [comment]
@skysbsb 

You can remove permissions using the `/r` switch of [dsacls](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc771151(v%3Dws.11))

It will be something like `dsacls "dc=rond, dc=local" /R "rond.local\david"`

**Comment by skysbsb** [comment]
> @skysbsb
> 
> You can remove permissions using the `/r` switch of [dsacls](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc771151(v%3Dws.11))
> 
> It will be something like `dsacls "dc=rond, dc=local" /R "rond.local\david"`

someone else suggested running:

dsacls "dc=rond,dc=local" /R "david@rond.local:CA;ms-Mcs-AdmPwd;computer" /I:S

what do you think?

**Comment by ryannewington** [comment]
@skysbsb if you are not comfortable using the command line, you can use Active Directory Users and Computers. Right-click on the top level domain object and select properies. From there, in the security tab, you will be able to see and remove the delegation.

**Comment by skysbsb** [comment]
ok tks
