### ISSUE TITLE
Add support for not expiring the LAPS password on access

### ISSUE THREAD

**Issue by mengdahuang** [lithnet/laps-web#20]
Hi, Sir

Thanks too much to share this great tools. however,  i don't want using the option "expire-after", i want control it via GPO. but when i choose remove this Property or set the vault to "false" then it going wrong.

Below are the logs
“2019-12-23 15:43:12.6341|ERROR|An unhandled error occurred while processing the request for the password for PC by user jasonSystem.FormatException: ...................... TimeSpan   .. System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName)”

could you help on this issue? thanks！
Kind regards

**Comment by ryannewington** [comment]
@mengdahuang 

What happens if you remove the expires-after element altogether. So instead of

```xml
<target name="OU=Workstations,DC=dev1,dc=local" 
            type="Container" 
            expire-after="03:00:00">
```

you'll just have

```xml
<target name="OU=Workstations,DC=dev1,dc=local" 
            type="Container">
```

**Comment by mengdahuang** [comment]
> @mengdahuang
> 
> What happens if you remove the expires-after element altogether. So instead of
> 
> ```
> <target name="OU=Workstations,DC=dev1,dc=local" 
>             type="Container" 
>             expire-after="03:00:00">
> ```
> 
> you'll just have
> 
> ```
> <target name="OU=Workstations,DC=dev1,dc=local" 
>             type="Container">
> ```

Hi，Sir
Certainly， I've tried remove the parameter "expire-after" from the target, and it shows the error
|ERROR|An unhandled error occurred while processing the request for the password for PC by user jasonSystem.FormatException: ...................... TimeSpan .. System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName)”

**Comment by ryannewington** [comment]
@mengdahuang,

Try this build and let me know how you go

https://github.com/lithnet/laps-web/releases/tag/v1.0.7320

Remember to backup your web.config file first

**Comment by mengdahuang** [comment]
> @mengdahuang,
> 
> Try this build and let me know how you go
> 
> https://github.com/lithnet/laps-web/releases/tag/v1.0.7320
> 
> Remember to backup your web.config file first

Dear Sir,

Thank you so much ! the issue fixed in this version.
