### ISSUE TITLE
The computer pc$ requested by user did not have a LAPS password in the directory

### ISSUE THREAD

**Issue by marcohald** [lithnet/laps-web#21]
I have laps-web installed with a Service Account with permissions to read and reset the Passwords.
When i try to get a Password i get "The computer pc$ requested by user did not have a LAPS password in the directory" in the Eventlog
When i run the LAPS-GUI with the same user Account i can get the Password.
What is the best way to debug this Problem ?

**Comment by ryannewington** [comment]
@marcohald,

Is the LAPS web app in the same domain as the AD where the computer object is stored?

If it is, it's almost certainly a permissions issues reading the LAPS password from AD. Can I double check you ran these commands to delegate permission? https://github.com/lithnet/laps-web/wiki/Configure-LAPS-service-account-permissions

And double check that the IIS application pool is running as that service account (Step 3 https://github.com/lithnet/laps-web/wiki/Installing-the-app#installation-procedure)

**Comment by marcohald** [comment]
@ryannewington ,

thank you for the Hint to the IIS application pool. I haven't changed it to the one i created during the Installlation.
Now it works perfect.
