### ISSUE TITLE
Windows authentication

### ISSUE THREAD

**Issue by vadimik** [lithnet/laps-web#22]
Hello,

May be it is silly question what is the best and easiest solution to restrict access to laps-web using configured WindowsAuth, if we have windows domain and iis? I mean that only group of domain users 
should have ability to sing in to laps-web site?

 <add key="owin:appStartup" value="Lithnet.Laps.Web.Startup.ConfigureWindowsAuth" />

**Comment by ryannewington** [comment]
Hi @vadimik,

There are two steps, the first is to tell the app that you want to use Windows Auth by modifying the web.config file, and configuring Windows Auth in IIS

https://github.com/lithnet/laps-web/wiki/Authentication-options#setting-up-windows-authentication

The second step is to configure your authorization in the web.config file. You can use this guide to look at the various configuration options.

https://github.com/lithnet/laps-web/wiki/Permissions

If you have any specific questions about the set up, do let me know.

**Comment by vadimik** [comment]
Thanks ryannewington!
