### ISSUE TITLE
You are not authorized to access the password for this computer

### ISSUE THREAD

**Issue by elsanc** [lithnet/laps-web#23]
Hi,
I installed and configured LAPS in my environment, computers are already receiving local user management; I liked the project and followed the LAPS-Web installation guides, but when I consult a managed computer, I receive the notification that "You are not authorized to access the password for this computer".

![image](https://user-images.githubusercontent.com/60203800/72946554-0cd92900-3d5e-11ea-9a08-dd5c77ad0e4f.png)

![image](https://user-images.githubusercontent.com/60203800/72946618-33975f80-3d5e-11ea-99f5-ebaa96963387.png)

![image](https://user-images.githubusercontent.com/60203800/72946645-4b6ee380-3d5e-11ea-8153-c8456f6a5c47.png)

**Comment by ryannewington** [comment]
Hey @elsanc 

Can you post your web.config file, or email it to support@lithnet.io

**Comment by elsanc** [comment]
> Hey @elsanc
> 
> Can you post your web.config file, or email it to [support@lithnet.io](mailto:support@lithnet.io)

Yes. The file sent by e-mail
