### ISSUE TITLE
Enable 2FA - TOTP

### ISSUE THREAD

**Issue by fjavierc** [lithnet/laps-web#24]
First of all, thanks for providing this fantastic tool.

My question or enhanced is whether it would be very difficult to enable 2FA in the authentication process. Personally I would like users who access laps-web also use TOTP, with Google Authenticator, FreeOTP, andOTP or similar.

Thanks

**Comment by ryannewington** [comment]
Hi @fjavierc 

Thanks for the kind feedback. 

Our supported way of offering MFA is to have the app hand off authentication to your favourite open id connect provider such as azure ad, okta, auth0, etc as per the [authentication setup guide](https://github.com/lithnet/laps-web/wiki/Authentication-options). 

From there you can use whatever mfa options are offered by the authentication provider. 

Unfortunately, as the app actually hands off the authentication process, we don’t have a way to offer mfa directly within the app itself.
