### ISSUE TITLE
Add support for searching all targets for an applicable ACL

### ISSUE THREAD

**Issue by sylwester-majcher** [lithnet/laps-web#28]
Hi,
This is rather request about improvement istead of reall issue.
I mean about target matching especially for the group.
Let image the situation the computer is in the severall groups but it can have different principals.
Normally based on the documentation 
https://github.com/lithnet/laps-web/wiki/Permissions#target-matching 
even if I am principal for one of a group I can be block to read password becuase LAPS Web has written fom web.config line from target as first line the group where the computer is include but principal not qual to me even if in the next line on the targets I am inside the principal...
Maybe it is possible only for Group type of target create some loop to don't close the procedure after first deny action?
I know in this king of situation I can use target type of Computer but it is not comfortable situation thinking about lot of tasks.
Thanks a lot!

**Comment by ryannewington** [comment]
@sylwester-majcher 

I've come across this issue, and will look to resolve it in a future version. I actually want to make the permission model a lot simpler and move it out of the web.config file. I agree that we should allow checking all the targets for a match before rejecting the request. This would be more consistent with how windows permissions work.

Ryan

**Comment by sylwester-majcher** [comment]
Hi Ryan,

In fact managing permissions in web.config for me this is not a problem only this rejecting after first checking.
Thanks a lot for your answer and I really wait new release of the tool!
Have a good day!
Sylwester





Pozdrawiam
Sylwester Majcher
________________________________
Od: Ryan Newington <notifications@github.com>
Wysłane: Wednesday, May 20, 2020 12:09:46 AM
Do: lithnet/laps-web <laps-web@noreply.github.com>
DW: sylwester-majcher <sylwester.majcher@outlook.com>; Mention <mention@noreply.github.com>
Temat: Re: [lithnet/laps-web] Target matching question (#28)


@sylwester-majcher<https://github.com/sylwester-majcher>

I've come across this issue, and will look to resolve it in a future version. I actually want to make the permission model a lot simpler and move it out of the web.config file. I agree that we should allow checking all the targets for a match before rejecting the request. This would be more consistent with how windows permissions work.

Ryan

**Comment by sylwester-majcher** [comment]
Hi Ryan,
How do you do?
I hope you are doing fine!
Can I ask my issue/evolution of your tool?
you think to build new relase?
Best regards
Sylwester

**Comment by ryannewington** [comment]
@sylwester-majcher I'm working on the next version at the moment. There are lots of changes, but this one has already been done. All targets will be processed for a match. I've still got quite a bit to do, but I'm expecting a release in the next month or two

**Comment by sylwester-majcher** [comment]
@ryannewington This is a fantastic news! Thanks and have a good day! I really thanks for your great tool that improve totally working with laps passwords.

**Comment by ryannewington** [comment]
@sylwester-majcher 

I've implemented this feature in the replacement for laps-web, which is now Lithnet Access Manager. You can check out the feature in the beta version released today.

https://github.com/lithnet/access-manager/releases/tag/v1.0.7596-beta.1

Ryan
