### ISSUE TITLE
Matched Reader Principal in email doesn't match

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/laps-web#29]
So I'm testing LAPS WEB as a tool for our company. 

I've now got an email that I've successfully requested a password except Matched Reader Principal in the email doesn't match the group that my user is in. I have 2 groups in test config

```xml
        <readers>
          <reader principal="DOMAIN1\Domain Admins" />
          <reader principal="DOMAIN2\Domain Admins" />
        </readers>
```

My user is in DOMAIN2\Domain Admins and it is showing wrong reader principal. (1st one).

**Comment by ryannewington** [comment]
@PrzemyslawKlys can you share your app log file? If you don't want to paste here, you can email to me at ryan@lithnet.io+

**Comment by ryannewington** [comment]
@PrzemyslawKlys did we get this one solved?

**Comment by PrzemyslawKlys** [comment]
No ;) Lemme try to get the logs

**Comment by PrzemyslawKlys** [comment]
Or maybe lets close it for now. I will move to new version and see how it is there. No sense in fixing old stuff :-)
