### ISSUE TITLE
Minor typos LAP instead of LAPS?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/laps-web#30]
I know it's just a minor typo or some other reason but it seems weird:
- The title of an email says LAP for PC$ accessed by ... - I guess by default it should be LAPS?
- URL to access LAPS -> http://mydomain/Lap/Get - I guess it should be Laps?

Or am I just misreading it and LAP makes some sense ?:)

**Comment by ryannewington** [comment]
I'm working on v2 at the moment, and the email subject is configurable in that version.

But LAP is short for '**local admin password** for PC$ accessed by'
Otherwise it would be '**local admin password solution** for PC$ accessed by' which wouldn't make sense.

**Comment by PrzemyslawKlys** [comment]
Tnx
