### ISSUE TITLE
The requested computer does not have a LAPS password

### ISSUE THREAD

**Issue by relzinga1** [lithnet/laps-web#31]
I have read a couple of your cases where the error "The requested computer does not have a LAPS password" was a problem and I have tried using the all of the commands below and they run successfully. I went into ADSI and made sure I had the special permissons on those OUs. I even deleted my service account and rebuilt it. LAPS works fine from the UI that LAPS/MS provides, but I continue to get. "The requested computer does not have a LAPS password". What else can I check? Thanks in advance!

dsacls "<DN of OU>" /G "<DOMAIN>\<sAMAccountName>:CA;ms-Mcs-AdmPwd;computer" /I:S
DSACLS "<DN of OU>" /G "<DOMAIN>\<sAMAccountName>:RPWP;ms-Mcs-AdmPwdExpirationTime;computer" /I:S
Set-AdmPwdReadPasswordPermission -Identity "OU=SERVERs,DC=us,DC=xxxx,DC=local" -AllowedPrincipals "xxxx\gmsa_laps$"
Set-AdmPwdResetPasswordPermission -Identity "OU=SERVERs,DC=us,DC=xxxx,DC=local" -AllowedPrincipals "xxxx\gmsa_laps$"

**Comment by ryannewington** [comment]
@relzinga1 can you tell me a bit about your domain structure. Is the Lithnet LAPS web app running in the same domain and forest as the target computer?

**Comment by relzinga1** [comment]
We do have multiple domains but everything I am doing here is all contained in one domain.

Thank you,
Roger Elzinga

**Comment by ryannewington** [comment]
I'm just wondering if there is something going on with the gmsa. Have you tried using a normal account just to test. I can't think of why a gmsa wouldn't work, but it's worth a shot. At least you can also confirm that the service account can read laps passwords with the native client as well. The Poweshell cmdlets you are using should be all that is required

**Comment by ryannewington** [comment]
@relzinga1 did you need any additional help with this?
