### ISSUE TITLE
Authentication filtering at an application level

### ISSUE THREAD

**Issue by pconnell247** [lithnet/laps-web#33]
For a Lithnet LAPS deployment that uses AD FS for authentication, does Lithnet LAPS have a way to perform authentication to the WebGUI at the application level as opposed to higher up at the AD FS server level?

**Comment by ryannewington** [comment]
Hey @pconnell247 

I'm not sure I understand the question. Can you describe the scenario you're trying to accommodate.

**Comment by pconnell247** [comment]
Hey @ryannewington 
Sorry i was unclear. Is there a way within Lithnet LAPS to restrict who is able to login to the Web GUI interface? I guess i am asking if there is a login page that can be enabled where authentication restrictions can be applied to only allow specific users to login

The scenario i am trying to accommodate is at present the Lithnet LAPS instance i have spun up allows everyone with an Active Directory user account within the domain to login to Lithnet LAPS and see a place they can interact with. Those queries are restricted to 1 individual workstation for 1 individual group via targets within web.config , but ideally i would like to prevent people even seeing the Lithnet LAPS Web GUI itself.

The back story is my current workplace typically runs a clean AD FS configuration, and pushes logic such as login authentication on the applications that are deployed within the environment. Restrictions can definitely be applied at the AD FS end of things, but hoping something can be enabled at the App level.

Thanks

**Comment by ryannewington** [comment]
Thanks for the additional explanation @pconnell247. I understand what you are trying to achieve.

Unfortunately, the current version doesn't provide this functionality when using ADFS. Fine grained authorization is performed using the target mechanism in the web.config file, but if you want to broadly prevent people logging into the app, then you'll need to block this at the ADFS level with an appropriate authorization rule.

If you use integrated windows auth, then you can configure IIS can do this user-level filtering for you (using authorization rules in IIS). When using an external provider, it's expected that the provider performs the 'who's allowed to use the app' check and the app does the 'what can they do once they are in' checks.

I can certainly look to add this capability to the upcoming new version. I expect that version will spend at least a couple of months in beta before a production release, as it is a major release. Just to set expectations about timing.

**Comment by ryannewington** [comment]
@pconnell247 

I've implemented this feature in the replacement for laps-web, which is now Lithnet Access Manager. You can check out the feature in the beta version released today.

https://github.com/lithnet/access-manager/releases/tag/v1.0.7596-beta.1

I'll close this issue off, and if you have any issues with the implementation there, please feel free to open an issue in the new access-manager repository

Ryan
