### ISSUE TITLE
LAPS Expiry not optional

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/laps-web#34]
It seems LAPS expiry option seems to be required and not optional. If you don't set it you will get an error when trying to get password - I tried finding a way to edit Wiki but couldn't. 

Additionally can you describe what happens when you set expire in 2hours? Does it simply mean resetting date of LAPS in AD and then it can take X amount of hours/days to actually enforce anything on the workstation if it doesn't have connectivity?

**Comment by ryannewington** [comment]
Have a look at #20. You should just be able to delete the expires-after attribute.

**Comment by ryannewington** [comment]
Yes, we write a new expiry date to AD. The next time the laps agent on the pc runs, if it's passed the new expiry date, it will change the password.

**Comment by PrzemyslawKlys** [comment]
Right :-) So in some cases it can be days ;-) Thank you. Btw I saw Just-in-time on screenshot from new version - is this something else from current implementation?

**Comment by ryannewington** [comment]
Yep 😄 loootsss of new features and functionality in the new version
