### ISSUE TITLE
Restricted PC access email notify

### ISSUE THREAD

**Issue by Techie4Life83** [lithnet/laps-web#36]
Hi Ryan,

For a feature can we have restricted PCs, using groups maybe, that if someone changes a password in that group it can send an email out? I'm sure we can accomplish this with a SIEM or inside of event logs but thought it might be slicker to have laps-web do that though. Thoughts?

Or even summary emails go out for review. Once again this is overlap with SIEM but not everyone has those :).

**Comment by ryannewington** [comment]
@Techie4Life83 

One of your LAPS targets can actually be a group containing these computers. You can then set notification rules specifically for computers in that group. LAPS Web looks for computer targets, then group targets, before finally looking for ou-based targets.

You might also be interested in checking out the beta of Lithnet Access Manager. It's the new version of LAPS web, but much more powerful and lots more features. Especially around notifications.

https://github.com/lithnet/access-manager/wiki

**Comment by Techie4Life83** [comment]
Very cool. I will have to test it out and see what it can do for LAPS Web.

The Access Manager looks awesome. I cannot wait to try it out.
