### ISSUE TITLE
Windows Authentication Prompt

### ISSUE THREAD

**Issue by jdelhome3578** [lithnet/laps-web#38]
I am using Windows Authentication but when I go to LAPS Web url it prompts for username and password. Should it be using the current logged in user via http passthrough?

**Comment by ryannewington** [comment]
@jdelhome3578 

It should, if you have the server and client configured correctly. 

There's a LOT to check on this topic, however, it's not specific to the web app, as all this stuff is handled by IIS.

I'd start with a tool like this to troubleshoot your kerberos server-side config

https://github.com/SurajDixit/KerberosConfigMgrIIS

And of course, ensure that your web site is added to the 'intranet sites' zone (NOT 'trusted sites') in IE for it to work in IE, edge, and chrome.
