### ISSUE TITLE
Clarify expire-after TimeSpan parsing in documentation

### ISSUE THREAD

**Issue by spencerryan** [lithnet/laps-web#39]
The note for "expire-after" on the Permissions wiki page states 

> "....if this is set to 01:00:00 (1 hour)....." 

However it is very unclear that this is being fed right into .NET's TimeSpan.Parse and the results might not be what you expected. For example I originally set mine to 24:00:00 for 1 day however this resulted in 24 days, which is exactly what the .NET documentation says:

> For example, the value of hh, the hours component, must be between 0 and 23. Because of this, passing "23:00:00" to the Parse method returns a time interval of 23 hours. On the other hand, passing "24:00:00" returns a time interval of 24 days. Because "24" is outside the range of the hours component, it is interpreted as the days component.

Perhaps simply updating the note that uses mostly what the .NET docs have for examples would help clarify, something like this:

```
"6" or "6:00:00:00" or "6.00:00:00" --> 6 Days
"6:12" --> 6 Hours 12 Minutes
"6:12:14" --> 6 Hours 12 Minutes 14 Seconds
"24:00:00" --> Danger Will Robinson: 24 days, not 24 hours
```

**Comment by ryannewington** [comment]
@spencerryan Thanks for this contribution! A good pick up!

I've made the updates to the wiki as suggested.

https://github.com/lithnet/laps-web/wiki/Permissions#expire-after-data-format
