### ISSUE TITLE
for smtp mail sending where should i put credentials

### ISSUE THREAD

**Issue by elesh27** [lithnet/laps-web#4]
for smtp mail sending where should i put credentials

**Comment by ryannewington** [comment]
Hi @elesh27,

In your web.config file, there is a system.net/mail settings section. You add the credentials in the as per the example here

https://stackoverflow.com/questions/19233108/how-to-configure-smtp-settings-in-web-config

**Comment by elesh27** [comment]
> Hi @elesh27,
> 
> In your web.config file, there is a system.net/mail settings section. You add the credentials in the as per the example here
> 
> https://stackoverflow.com/questions/19233108/how-to-configure-smtp-settings-in-web-config

Thanks but after adding credentials, i am getting "emailSystem.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure." error in log file and mail is not sent.

**Comment by ryannewington** [comment]
You've enabled SSL in the config section, but the server's SMTP TLS certificate is not trusted by the client for some reason. It may be self-signed, contain a mismatched hostname, or out of date.
