### ISSUE TITLE
Lithnet LAPS web app not recognizing child domain

### ISSUE THREAD

**Issue by chadht** [lithnet/laps-web#41]
Hi. Is there a solution getting the Lithnet LAPS web app to recognize a child domain? I'm able to get the password for computers in the child domain using the LAPS UI but when I use the Lithnet LAPS web app it says the requested computer was not found in the directory. Any insight is appreciated. 

Thanks,
Chad

**Comment by ryannewington** [comment]
Hey @chadht 

I recommend you move over to the next generation of laps web, Lithnet Access Manager. 

https://github.com/lithnet/access-manager/wiki

It has full support for multi domain environments and tonnes of other improvements. 

While it's technically still in beta at the moment, the LAPS functionality is stable and supported for production use.

**Comment by ryannewington** [comment]
Alternatively [this comment](https://github.com/lithnet/laps-web/issues/10#issuecomment-542144374)  contains details of a build that support global catalog lookups for cross domain access. It will work in a simple child domain scenario, but access manager is the way to go for full support.

**Comment by chadht** [comment]
Hey Ryan,

Thanks for your quick response! I will look at the comment and also the access manager option.

Thanks,
Chad Tidgewell
Technology Support | HCPSS
techsupport@hcpss.org<mailto:techsupport@hcpss.org> | Technology Resources<https://hcpss.instructure.com/courses/32959>


The information contained in this email transmission is privileged and/or confidential and is intended solely for the exclusive use of the individual addressee. If you are not the intended addressee, you are hereby notified that any retention, disclosure, or other use is strictly prohibited. If you have received this email in error, please contact the sender immediately and delete the material.

**Comment by chadht** [comment]
Hi Ryan,

For now I decided use build v1.0.7320. I setup two servers that will host the LithnetLAPS web app, one for each or our domains. I have no problem finding computers on the parent domain using the LAPS UI or the LithnetLAPS web app. I’m able to find computers on the child domain using the LAPS UI but when I use the LithnetLAPS web app the message says “the requested computer was not found in the directory”. Any ideas of what might be causing the issue?

Thanks,
Chad Tidgewell
Technology Support | HCPSS
techsupport@hcpss.org<mailto:techsupport@hcpss.org> | Technology Resources<https://hcpss.instructure.com/courses/32959>


The information contained in this email transmission is privileged and/or confidential and is intended solely for the exclusive use of the individual addressee. If you are not the intended addressee, you are hereby notified that any retention, disclosure, or other use is strictly prohibited. If you have received this email in error, please contact the sender immediately and delete the material.

**Comment by ryannewington** [comment]
7320 doesn't have child domain support. 

I strongly recommend to just use access manager. One of the primary reasons it was written was to introduce multi domain and forest support. I had to rewrite the authorisation engine to properly support these scenarios. Laps web is supported for standalone domains only and isn't being developed further.
