### ISSUE TITLE
An unhandled error occurred while processing the request for the password for *computername* by user unknown

### ISSUE THREAD

**Issue by ryannewington** [lithnet/laps-web#43]
An unhandled error occurred while processing the request for the password for *computername* by user unknown
System.Runtime.InteropServices.COMException (0x8007200A): The specified directory service attribute or value does not exist.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_SchemaEntry()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.IsContainer(DirectoryEntry de)
   at System.DirectoryServices.AccountManagement.ADStoreCtx..ctor(DirectoryEntry ctxBase, Boolean ownCtxBase, String username, String password, ContextOptions options)
   at System.DirectoryServices.AccountManagement.PrincipalContext.CreateContextFromDirectoryEntry(DirectoryEntry entry)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, IdentityType identityType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, IdentityType identityType, String identityValue)
   at Lithnet.Laps.Web.Controllers.LapController.GetCurrentUser() in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 222
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 43

_Originally posted by @sceptapular in https://github.com/lithnet/laps-web/issues/19#issuecomment-767791007_

**Comment by ryannewington** [comment]
@sceptapular I've moved this to a new issue as its unrelated to the other closed issue

**Comment by ryannewington** [comment]
Do the suggestions in this article help? Eg have permissions on the users or computers container in the domain been restricted?

https://medium.com/markus-blog/authentication-problems-with-principalcontext-cc0a0489867c

**Comment by ryannewington** [comment]
(not the code changes, but the permission changes as the root cause)

**Comment by sceptapular** [comment]
Ryan:
Firstly, thank you for the legendary quick response!
I did make progress after adding the LAPS service account to Domain Admins for now; now, the error says " You are not authorized to access the password for this computer" .  I'm looking into it.

**Comment by sceptapular** [comment]
I am also accessing LAPSweb with a domain admin account.

**Comment by ryannewington** [comment]
@sceptapular that means you need to create an authorisation rule for that user

https://github.com/lithnet/laps-web/wiki/Permissions

**Comment by sceptapular** [comment]
I suspected as much, and I pored over my web.config file.  I even added
myself directly, in addition to my membership in the originally-defined
security group.  I even moved my test computer into the immediate OU
referenced, in case it wasn't reading sub-OUs well.  Must be something
simple somewhere...hmmm...

Crazy question - do you have a few minutes to spare and look over my
setup?  I'd pay you.  My last day here is Friday, and I'd love to leave
this in working order.

**Comment by sceptapular** [comment]
My anon web.config file follows:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <configSections>
    <section name="lithnet-laps" type="Lithnet.Laps.Web.LapsConfigSection"
/>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
  </configSections>
  
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="laps-eventlog" xsi:type="EventLog" source="LAPSWeb"
log="Application" layout="${message}${newline}${exception:format=ToString}"
eventId="${event-properties:EventID:whenEmpty=1}" />
      <target name="laps-file" xsi:type="File"
fileName="app_data/logs/lapsweb.log" archiveEvery="Day"
archiveNumbering="Date" maxArchiveFiles="7" concurrentWrites="true"
layout="${longdate}|${level:uppercase=true:padding=5}|${message}${exception:format=ToString}"
/>
    </targets>
    <rules>
      <logger minlevel="Info" writeTo="laps-eventlog" name="*" />
      <logger minlevel="Trace" writeTo="laps-file" name="*" />
    </rules>
  </nlog>
  <appSettings file="secrets.config">
    
    
    <add key="owin:appStartup"
value="Lithnet.Laps.Web.Startup.ConfigureWindowsAuth" />
    
    
    
    
    
    
    <add key="app:Title" value="Our Local Admin Password Solution" />
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
  </appSettings>
  
  <system.net>
    <mailSettings>
      <smtp deliveryMethod="Network" from="laps@domain.com">
        <network host="smtp.domain.com" port="25"
defaultCredentials="false" enableSsl="false" />
      </smtp>
    </mailSettings>
  </system.net>
  <lithnet-laps>
    <audit emailOnSuccess="true" emailOnFailure="true" emailAddresses="
me@domain.com" />
    <rate-limit-ip enabled="true" requestsPerMinute="5"
requestsPerHour="50" requestsPerDay="100" rateLimitOnXffIP="false" />
    <rate-limit-user enabled="true" requestsPerMinute="5"
requestsPerHour="50" requestsPerDay="100" />
    
  </lithnet-laps>
  <system.web>
    <compilation targetFramework="4.6.1" />
    <httpRuntime targetFramework="4.6.1" />
    <httpModules />
    <globalization enableClientBasedCulture="true" uiCulture="auto"
culture="auto" />
  </system.web>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Antlr3.Runtime"
publicKeyToken="eb42632606e9261f" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.2" newVersion="3.5.0.2"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource"
publicKeyToken="cc7b13ffcd2ddd51" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.1" newVersion="4.0.2.1"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json"
publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0"
newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization"
publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease"
publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930"
newVersion="1.6.5135.21930" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers"
publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages"
publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc"
publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.4.0" newVersion="5.2.4.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity
name="Microsoft.IdentityModel.Protocols.OpenIdConnect"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Tokens"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.2.0" newVersion="5.2.2.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocols"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http"
publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity
name="Microsoft.IdentityModel.Protocols.WsFederation"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Tokens.Saml"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.2.0" newVersion="5.2.2.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Logging"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.2.0" newVersion="5.2.2.0"
/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Xml"
publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.2.0" newVersion="5.2.2.0"
/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
    <httpProtocol>
      <customHeaders>
        <add name="Content-Security-Policy" value="default-src 'none';
script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';
font-src 'self';" />
      </customHeaders>
    </httpProtocol>
    <staticContent>
      <remove fileExtension=".woff" />
      <mimeMap fileExtension=".woff" mimeType="font/woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff2" mimeType="font/woff" />
    </staticContent>
  </system.webServer>
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs"
type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider,
Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.8.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4"
compilerOptions="/langversion:default /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb"
type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider,
Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.8.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4"
compilerOptions="/langversion:default /nowarn:41008
/define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
</configuration>

**Comment by sceptapular** [comment]
My account is part of 'Domain Admins'. The computers are either within the referenced 'Computers' OU or in its subfolders.  As my account, I have full admin rights on all client PCs.  I have even directly specified myself as administrator on a test PC.

Also, after making a web.config change, does anything need to be done to apply it?  restarting the website? IIS?  rebooting the target client?...

**Comment by sceptapular** [comment]
Amateur hour!  Targets section was still commented.  SUCCESS!!!

**Comment by ryannewington** [comment]
Excellent! Yes sorry this traps quite a few people. The next version of this app is all driven from a configuration UI so hopefully this sort of confusion is a thing of the past soon!

**Comment by Dlm0n64** [comment]
Hi Everyone!

I have the issue with getting a password.
You can see the log below
---------------------------------------------
System.DirectoryServices.DirectoryServicesCOMException (0x80072030): There is no such object on the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at System.DirectoryServices.DirectorySearcher.FindOne()
   at Lithnet.Laps.Web.ActiveDirectory.ActiveDirectory.IsComputerInOu(IComputer computer, String ou) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\ActiveDirectory\ActiveDirectory.cs:line 56
   at Lithnet.Laps.Web.Security.Authorization.AvailableTargets.GetMatchingTargetOrNull(IComputer computer) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Security\Authorization\AvailableTargets.cs:line 29
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 103
------------------------------------------------

So, the steps which I've done:
- All permissions have been granted to appropriate OU.
- Read\write access has been granted to Service Account for IIS pool.

I can get a password via FAT client GUI but can't via WEB.
Also I've checked getting a password by PowerShell with credentials of Service Account - it's works.

Please help resolve this issue.

Thanks in advance!

**Comment by Dlm0n64** [comment]
Hi Everyone!

I have the issue with getting a password.
You can see the log below

System.DirectoryServices.DirectoryServicesCOMException (0x80072030): There is no such object on the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at System.DirectoryServices.DirectorySearcher.FindOne()
   at Lithnet.Laps.Web.ActiveDirectory.ActiveDirectory.IsComputerInOu(IComputer computer, String ou) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\ActiveDirectory\ActiveDirectory.cs:line 56
   at Lithnet.Laps.Web.Security.Authorization.AvailableTargets.GetMatchingTargetOrNull(IComputer computer) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Security\Authorization\AvailableTargets.cs:line 29
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 103


So, the steps which I've done:
- All permissions have been granted to appropriate OU.
- Read\write access has been granted to Service Account for IIS pool.

I can get a password via FAT client GUI but can't via WEB.
Also I've checked getting a password by PowerShell with credentials of Service Account - it's works.

Please help resolve this issue.

Thanks in advance!

**Comment by Dlm0n64** [comment]
And one more important thing is that application has worked perfect few month ago.
I didn't catch the moment when the issue happened.

**Comment by ryannewington** [comment]
@Dlm0n64  I've moved your comment to a new issue, as it is unrelated to the issue logged here. Let's continue the conversation in #47
