### ISSUE TITLE
Timezone differences?

### ISSUE THREAD

**Issue by shift-faced** [lithnet/laps-web#45]
How does this app work when the executing computer is in the PST timezone and the target timezone is in EST?
I just retrieved a LAPS password for a user (configured to expire in 2 hours) at 12pm PST and sent it to him in NYC. He's saying it didn't work. Is it because it's already "past" 2 hours in New York?

**Comment by ryannewington** [comment]
The times are stored in utc in AD, so time zones do not matter in this sense. 

Also keep in mind that laps client checks for password expiry on gp refresh, so the password is going to expire on the next gp refresh *after* the expiry time specified (could be up to 90mins after the specified expiry time).

**Comment by shift-faced** [comment]
Gotcha, thank you for the confirmation. That's great to know. Turns out the user was using the wrong username lol. I got him squared away.
I shall close this.
