### ISSUE TITLE
"There is no such object on the server" error when trying to match targets

### ISSUE THREAD

**Issue by ryannewington** [lithnet/laps-web#47]
Hi Everyone!

I have the issue with getting a password.
You can see the log below

System.DirectoryServices.DirectoryServicesCOMException (0x80072030): There is no such object on the server.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at System.DirectoryServices.DirectorySearcher.FindOne()
   at Lithnet.Laps.Web.ActiveDirectory.ActiveDirectory.IsComputerInOu(IComputer computer, String ou) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\ActiveDirectory\ActiveDirectory.cs:line 56
   at Lithnet.Laps.Web.Security.Authorization.AvailableTargets.GetMatchingTargetOrNull(IComputer computer) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Security\Authorization\AvailableTargets.cs:line 29
   at Lithnet.Laps.Web.Controllers.LapController.Get(LapRequestModel model) in D:\dev\git\lithnet\laps-web\src\Lithnet.Laps.Web\Lithnet.Laps.Web\Controllers\LapController.cs:line 103

So, the steps which I've done:
- All permissions have been granted to appropriate OU.
- Read\write access has been granted to Service Account for IIS pool.

I can get a password via FAT client GUI but can't via WEB.
Also I've checked getting a password by PowerShell with credentials of Service Account - it's works.

Please help resolve this issue.

Thanks in advance!

_Originally posted by @Dlm0n64 in https://github.com/lithnet/laps-web/issues/43#issuecomment-811834696_

**Comment by ryannewington** [comment]
@Dlm0n64

This is usually due to a typo in one of the OU targets in your web.config file. Double check all the targets. If they appear correct, please send your config file to support@lithnet.io

**Comment by Dlm0n64** [comment]
> 
> 
> @Dlm0n64
> 
> This is usually due to a typo in one of the OU targets in your web.config file. Double check all the targets. If they appear correct, please send your config file to [support@lithnet.io](mailto:support@lithnet.io)

Hello Ryannewington,

Thanks for quick response.
Yep, you're right.
There was an OU bug. One of the OU has been removed\renamed in AD schema and web configuration has malfunction. 
As soon as I found this bug it began to work properly.

Could you also clarify please are there any restrictions about on the numbers of OUs in the config file ?  (I have more than hundred of it)

**Comment by ryannewington** [comment]
@Dlm0n64 

Glad to hear you got it working. 

There is no practical limit on the number of OUs in your config file, however, performance may not be too good if there are too many. 

You might want to have a look at Access Manager, which will soon be replacing Laps Web. This has been tuned for large numbers of rules, and you can import your rules from LAPS web directly into the new app. https://github.com/lithnet/access-manager.

**Comment by Dlm0n64** [comment]
> 
> 
> @Dlm0n64
> 
> Glad to hear you got it working.
> 
> There is no practical limit on the number of OUs in your config file, however, performance may not be too good if there are too many.
> 
> You might want to have a look at Access Manager, which will soon be replacing Laps Web. This has been tuned for large numbers of rules, and you can import your rules from LAPS web directly into the new app. https://github.com/lithnet/access-manager.


Yes, I saw the link to the new app, thank you.
So far, we are satisfied with this solution, the simpler the better 

Is there any fix solution to avoid this kind of bug?. So that when you change the AD schema, the config file works as usual without errors and just skips the OU that was not found

**Comment by ryannewington** [comment]
Unfortunately not. This particular issue is fixed in access manager, however we aren't investing in any more changes to the laps web code base.
