### ISSUE TITLE
Targets in XML file

### ISSUE THREAD

**Issue by Afsars12** [lithnet/laps-web#51]
Hi Team,

Please help me in understanding targets in the XML file.

I have 10 targets in an XML file with its associated readers, all were working properly. One OU got decommissioned without our knowledge, and we started receiving **unknown error occurred** in the application. After removing the decommissioned OU/target application we are able to retrieve the passwords.

How can we bypass this error, in case of any OU gets decommissioned? 

Kindly advice.

**Comment by ryannewington** [comment]
Hi @Afsars12,

That's a known issue with LAPS web. It's successor, [Lithnet Access Manager](https://github.com/lithnet/access-manager) does not have this issue.
